<a href="https://colab.research.google.com/github/samp-suman/Data-Analysis/blob/master/suman_kumar_suman_Numpy_assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
# Setup for questions 1 and 2
arr1=np.arange(40).reshape(8,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [0]:
# Q1. From arr1 you have to fetch out every alternate column starting from col1

In [0]:
# Q2. From arr1 fetch an array which would contain {0,2,4} {15,17,19} and {30,32,34} 

In [0]:
# Setup for question

# Generating a random numpy array of intergers ranging between 1 and 10000

arr2=np.random.randint(low=1, high=10000, size=10).reshape(2,5)
arr2

array([[7736, 5162, 2606, 3332, 4846],
       [9000, 7109, 8375, 3615, 5048]])

 **Normalization** rescales the values into a range of [0,1]. This might be useful in some cases where all parameters need to have the same positive scale. You have to do this a lot in machine learning for eg you are working with 2 cols, one is total runs scored by a batsman(in the scale of 1000s), and the second is number of matches played by him(in the scale of 10s). The formula for normalization is given below

 Xchanged=(X−Xmin)/(Xmax−Xmin)

In [0]:
# Q3. Write a code to normalize arr2.

In [0]:
np.percentile(arr1,25)

9.75

Missing values are a pain in the a**(sorry for language). But yes trust me.

In [0]:
# Q4. How would you check if your numpy array has some missing values?

# Hint: Thoda research karo numpy me existing functions hai

In [0]:
# Q5. Write a function which will accept 2 arguments.
# First: A 1D numpy array arr
# Second: An integer n {Please make sure n<=len(arr)}

# Output: The output should be the nth largest item out of the array

# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40

**[From Here Answer starts](https://)**

In [0]:
#Q1. From arr1 you have to fetch out every alternate column starting from col1
#ans1: 
#Using slicing in index 
q1=arr1[:,0::2]


In [0]:
q1

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19],
       [20, 22, 24],
       [25, 27, 29],
       [30, 32, 34],
       [35, 37, 39]])

In [0]:
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [0]:
# Q2. From arr1 fetch an array which would contain {0,2,4} {15,17,19} and {30,32,34} 
#ans2: 
# {0,2,4}-- 1st,3nd and 5th column, that is alternate column from 1st col.
# {0,15,30}-- 1st, 4th and 6th row, that is gap of 2 from 1st row
# combining both will give our result
q2=arr1[::3,::2]
q2

array([[ 0,  2,  4],
       [15, 17, 19],
       [30, 32, 34]])

In [0]:
# Setup for question

# Generating a random numpy array of intergers ranging between 1 and 10000

arr2=np.random.randint(low=1, high=10000, size=10).reshape(2,5)
arr2

array([[ 101, 4940, 9953, 6664, 7564],
       [8982, 3831, 2377, 9009, 2629]])

 **Normalization** rescales the values into a range of [0,1]. This might be useful in some cases where all parameters need to have the same positive scale. You have to do this a lot in machine learning for eg you are working with 2 cols, one is total runs scored by a batsman(in the scale of 1000s), and the second is number of matches played by him(in the scale of 10s). The formula for normalization is given below

 Xchanged=(X−Xmin)/(Xmax−Xmin)

In [0]:
# Q3. Write a code to normalize arr2.
# There are many method of Normalising-- simple, min-max, z-score or standard score
# Here below i have done by method Simple Feature scaling that is-- Xnew=Xold/Xmax
max=arr2.max()
min=arr2.min()
narray=arr2/max
narray


array([[0.01014769, 0.49633276, 1.        , 0.66954687, 0.75997187],
       [0.90244147, 0.38490907, 0.23882247, 0.90515422, 0.26414146]])

In [0]:
# method 2:- 
# Ans:- Excepted answer for 
# Formula as given in above example explanation that is-- Xnew=(Xold-Xmin)/(Xmax-Xmin)
# Min-Max method--
mmarray=(arr2-min)/(max-min)
mmarray

array([[0.        , 0.49116931, 1.        , 0.66615916, 0.75751117],
       [0.90144133, 0.37860333, 0.23101908, 0.90418189, 0.25659765]])

In [0]:
# method 3(For normalisation):- Formula as given in above example explanation that is-- Xnew=(Xold-Mean)/(standard deviation)
# Z - score Method or standard Method--
"""This method is not considered for the above problen as this method is not used for normalise data in [0,1]"""
mean=arr2.mean()
std=arr2.std()
zarray=(arr2-mean)/std
zarray

array([[-1.69035509, -0.01326406,  0.68130406, -0.53551278,  0.78144582],
       [-0.08279645, -1.24255138,  0.81885727, -0.5283328 ,  1.81120541]])

In [0]:
# Q4. How would you check if your numpy array has some missing values?

# Hint: Thoda research karo numpy me existing functions hai
#Ans4 - Research kr rhe hain 
# There is a function "np.isnan()".. but having problenm in passing arguments here like below
# "TypeError: ufunc 'isnan' not supported for the input types, 
#           and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''"

In [0]:
# Not as like isnan() but it check wether any dataa is missing or not
def check(arr):
    if np.nan in arr:
        return print("missing values")
    else:
        return print("no values missing")
check(narray)
    

no values missing


In [0]:
ar8=[1,2,np.nan,np.nan,90,88.0,90.0,np.nan]

In [0]:
check(ar8)

missing values


In [0]:
# After research foud out this function return an boolean array, 'True' represents data is missing  

np.isnan(ar8) # here worked bingo..

array([False, False,  True,  True, False, False, False,  True])

In [0]:
# Q5. Write a function which will accept 2 arguments.
# First: A 1D numpy array arr
# Second: An integer n {Please make sure n<=len(arr)}

# Output: The output should be the nth largest item out of the array

# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40

In [0]:
#ans5:
#First sorted the array then return the last nth value of the array.
#
#
def nthmax(arr,n):
    if n<=len(arr):
        arr.sort()
        return arr[-n]
    else:
        raise IndexError('n should not exceed the length of the array {}, which is {}, \n The value of n was: {}'.format(arr,len(arr),n))
a1=np.array([10,18,11,45,78,32])
nthmax(a1,4)

18

In [0]:
#Test1:
a2=np.array([12,34,40,7,1,0])
nthmax(a2,3)

12

In [0]:
# Test2:
a3=np.array([12,34,40,7,1,0])
nthmax(a3,1)
    

40