<a href="https://colab.research.google.com/github/samp-suman/Data-Analysis/blob/master/suman_kumar_suman_numpy_assignment_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
arr1=np.arange(20).reshape(4,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [0]:
# Q1 Write a numpy code to swap col1([0,5,10,15]) with col4([3,8,13,18])
# Hint----> Fancy Indexing
#Ans1: 
arr1[:,[0,3]]=arr1[:,[3,0]]
arr1

array([[ 3,  1,  2,  0,  4],
       [ 8,  6,  7,  5,  9],
       [13, 11, 12, 10, 14],
       [18, 16, 17, 15, 19]])

In [0]:
# Q2 Write a numpy code to reverse the rows of arr1
# The output should be [15, 16, 17, 18, 19] as first row and [ 0,  1,  2,  3,  4] as last row
#Ans2:-
arr=arr1[-1::-1]
arr

array([[15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [0]:
arr2=np.array([[1,2,np.nan],[4,5,6],[np.nan,np.nan,9]])
arr2

array([[ 1.,  2., nan],
       [ 4.,  5.,  6.],
       [nan, nan,  9.]])

In [0]:
# Q3 Write a code to replace all the nan(missing values) of arr2 with the mean of arr2
#Ans3:=
#Using 'isnan()'' function with fancy indexing here and then replace it by mean(using 'mean()' function)
arr2[np.isnan(arr2)]=arr2[~np.isnan(arr2)].mean()
arr2

array([[1. , 2. , 4.5],
       [4. , 5. , 6. ],
       [4.5, 4.5, 9. ]])

In [0]:
#For Q4

arr3=np.random.randint(low=1,high=100,size=20).reshape(5,4)
arr3

array([[85,  4, 87, 52],
       [14, 75, 30, 32],
       [ 9, 79, 10, 11],
       [61, 47, 69,  1],
       [58, 33, 96, 54]])

In [0]:
# Q4 Write a code which can fetch all items from arr3 which are either greater than 25 or a multiple of 3
#ANS3:---

In [0]:
#Ans4:using fancy indexing (boolean type) applyin two contion at a time

arr3[(arr3>25) & (arr3%3==0)]

array([87, 75, 30, 69, 33, 96, 54])

In [0]:
# Q5 Write a code to find the 10th, 25th, 50th(median) percentile of arr3
# Percentiles are a very important concept in Statistics. If you don't know about it refer the video below
# https://www.youtube.com/watch?v=Snf6Wpn-L4c
# Hint: to solve this function google np.percentile()

#Ans5:
#Here is percentile function similar like numpy.percentile(...), in numpy there are differten method of interpolation
#here is use only one that is midpoint one.
def percentile(a,n):
    
    
    a=np.ravel(a)
    a.sort()
    #rank of the value which are at n percentile, it may result in fractional thats why we have to
    #figure out how to solve, for that there are different methods, here i used 'midpoint' one. others are 'linear','lower,'upper'.
    p=(n*(np.size(a)+1)/100)   
    if p%1==0:
        return a[int(p-1)]
    #The midpoint method is applied here, it results in avg of the two sorrounded value of the rank(p).
    else:                    
        return (a[int(p-1)]+a[int(p)])/2

In [0]:
p10=percentile(arr3,10)
p25=percentile(arr3,25)
p50=percentile(arr3,50)
p=[p10,p25,p50]
p

[6.5, 12.5, 49.5]

In [0]:
#Ans5:using numpy percentile function

p10=np.percentile(arr3,10,interpolation='midpoint')
p25=np.percentile(arr3,25,interpolation='midpoint')
p50=np.percentile(arr3,50,interpolation='midpoint')
print("P10th=",p10,"P25th=",p25,"P50th=",p50)

P10th= 6.5 P25th= 12.5 P50th= 49.5
